apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
      - name: payments-service
        image: acrfiaprodrigoborges.azurecr.io/tc-rodrigo-fiap-microservice-payments:latest
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     cpu: "100m"
        #     memory: "128Mi"
        #   limits:
        #     cpu: "250m"
        #     memory: "256Mi"
        env:
        - name: ConnectionStrings__Main
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: ConnectionStrings__Main
        - name: AuthKey
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: AuthKey
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: Jwt__Key
        - name: Jwt__Issuer
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: Jwt__Issuer
        - name: Jwt__Audience
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: Jwt__Audience
        - name: RabbitMq__Host
          valueFrom:
            secretKeyRef:
              name: payment-secrets
              key: RabbitMq__Host
---
apiVersion: v1
kind: Service
metadata:
  name: payments-service
spec:
  type: LoadBalancer # Cria um IP p√∫blico para acesso externo
  selector:
    app: payments-service
  ports:
  - port: 80
    targetPort: 8080
---
# Requisito de HPA (Auto Scaling)
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payments-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payments-service
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
